name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Package
      run: dotnet pack -c Release -o package --no-build

    - name: Publish nuget
      run: dotnet nuget push --source package/*.nupkg --skip-duplicate
